theme = "sonokai"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
mouse = false
true-color = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "┆"

[keys.insert]
# Maps `jk` to exit insert mode
j = { k = "normal_mode" } 
k = { j = "normal_mode" }

[keys.normal]
D = "kill_to_line_end"
